---
version: "3.3"
services:
  cooked:
    build: ./
    container_name: cooked
    ports:
      - 3000:3000
    restart: unless-stopped
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cooked
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
